<h1>Importing the Numpy <br>Loading and printing the dataset</h1>


In [2]:

import numpy as np

marks = np.load('../data/student_marks.npy')

'''
Subject Indexing:

0 -> Math
1 -> Science
2 -> English
3 -> Computer
'''

print("Student Marks:")
print(marks)


Student Marks:
[[78 85 72 90]
 [65 70 68 75]
 [92 88 85 95]
 [55 60 62 58]
 [81 79 88 84]
 [74 82 76 80]
 [88 91 84 89]
 [69 73 71 77]
 [95 94 91 97]
 [60 67 65 70]]


<h2>Basic Array Exploration</h2>

In [ ]:
print('Shape: ', marks.shape)
print('Dimensions: ', marks.ndim)
print('Size: ', marks.size)
print('Data Type: ', marks.dtype)

Shape:  (10, 4)
Dimentions:  2
Size:  40
Data Type:  int64


<h2>Indexing and Slicing</h2>

In [4]:
print('First Student Marks: ', marks[0])
print('First Student Math Marks: ', marks[0,0])
print('Third Student Computer Marks: ', marks[2,3])


First Student Marks:  [78 85 72 90]
First Student Math Marks:  78
Third Student Computer Marks:  95


In [5]:
print('Marks of first three students: \n', marks[:3])
print('Only Math marks of students: \n', marks[:,0])
print('Math and Science marks of students: \n', marks[:,0:2])
print('Marks of last two students: \n', marks[-2:])

Marks of first three students: 
 [[78 85 72 90]
 [65 70 68 75]
 [92 88 85 95]]
Only Math marks of students: 
 [78 65 92 55 81 74 88 69 95 60]
Math and Science marks of students: 
 [[78 85]
 [65 70]
 [92 88]
 [55 60]
 [81 79]
 [74 82]
 [88 91]
 [69 73]
 [95 94]
 [60 67]]
Marks of last two students: 
 [[95 94 91 97]
 [60 67 65 70]]


<h2>Mathematical Operation</h2>

In [6]:
bonus_marks = marks + 5

print('Increased Marks: \n', bonus_marks)

Increased Marks: 
 [[ 83  90  77  95]
 [ 70  75  73  80]
 [ 97  93  90 100]
 [ 60  65  67  63]
 [ 86  84  93  89]
 [ 79  87  81  85]
 [ 93  96  89  94]
 [ 74  78  76  82]
 [100  99  96 102]
 [ 65  72  70  75]]


In [7]:
print(marks * 2)

[[156 170 144 180]
 [130 140 136 150]
 [184 176 170 190]
 [110 120 124 116]
 [162 158 176 168]
 [148 164 152 160]
 [176 182 168 178]
 [138 146 142 154]
 [190 188 182 194]
 [120 134 130 140]]


<h2>Axis-wise Operation</h2>
<p> Axis = 0 --> down the rows --> column-wise <br> Axis = 1 --> across the column --> row-wise</p>

In [8]:
subject_avg = np.mean(marks, axis = 0)
student_avg = np.mean(marks, axis = 1)

print('Avg Marks by Subject: ', subject_avg)
print('Avg Marks by Student: ', student_avg)


Avg Marks by Subject:  [75.7 78.9 76.2 81.5]
Avg Marks by Student:  [81.25 69.5  90.   58.75 83.   78.   88.   72.5  94.25 65.5 ]


<h2>Statistical Analysis</h2>

In [9]:
print('Mean: ', np.mean(marks))
print('Median: ', np.median(marks))
print('Maximum: ', np.max(marks))
print('Minimum: ', np.min(marks))
print('Standard Deviation ', np.std(marks))
print('Total: ', np.sum(marks))


Mean:  78.075
Median:  78.5
Maximum:  97
Minimum:  55
Standard Deviation  11.439815339418727
Total:  3123


<h4>Subject-wise</h4>

In [10]:
print('Subject Mean: ', np.mean(marks, axis= 0))
print('Subject Median: ', np.median(marks, axis= 0))
print('Subject Maximum: ', np.max(marks, axis= 0))
print('Subject Minimum: ', np.min(marks, axis= 0))


Subject Mean:  [75.7 78.9 76.2 81.5]
Subject Median:  [76.  80.5 74.  82. ]
Subject Maximum:  [95 94 91 97]
Subject Minimum:  [55 60 62 58]


<h2>Reshaping</h2>

In [11]:
nums = np.arange(1,13)

print(nums)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [12]:
reshape = nums.reshape(2,6)

print(reshape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [14]:
print(reshape.shape)

(2, 6)


<h2>Broadcasting</h2>

In [18]:
#Adding different bonus marks in each subject

bonus = np.array([5, 4, 6, 2])

new_marks = marks + bonus

print(new_marks)

[[ 83  89  78  92]
 [ 70  74  74  77]
 [ 97  92  91  97]
 [ 60  64  68  60]
 [ 86  83  94  86]
 [ 79  86  82  82]
 [ 93  95  90  91]
 [ 74  77  77  79]
 [100  98  97  99]
 [ 65  71  71  72]]


<h2>Saving and loading the dataset</h2>

In [20]:
np.save('../data/updated_student_marks.npy', new_marks)

In [21]:
loaded_marks = np.load('../data/updated_student_marks.npy')
print(loaded_marks)

[[ 83  89  78  92]
 [ 70  74  74  77]
 [ 97  92  91  97]
 [ 60  64  68  60]
 [ 86  83  94  86]
 [ 79  86  82  82]
 [ 93  95  90  91]
 [ 74  77  77  79]
 [100  98  97  99]
 [ 65  71  71  72]]


<h2>Numpy VS Python List</h2>

In [27]:
import time

size = 1000000

python_list = list(range(size))
numpy_array = np.arange(size)

In [28]:
start = time.time()
result = [x * 2 for x in python_list]
list_time = time.time() - start

In [29]:
start = time.time()
result = numpy_array * 2
numpy_time = time.time() - start

In [30]:
print('Time taken by List: ', list_time)
print('Time taken by Numpy: ', numpy_time)


Time taken by List:  0.034629106521606445
Time taken by Numpy:  0.012064218521118164
